[tool.bumpversion]
current_version = "0.0.0"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "setup.py"
search = "version=\"{current_version}\""
replace = "version=\"{new_version}\""

[[tool.bumpversion.files]]
filename = "docs/conf.py"
search = "version = release = \"{current_version}\""
replace = "version = release = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "m2m_postaviz/__init__.py"
search = "__version__ = \"{current_version}\""
replace = "__version__ = \"{new_version}\""

[[tool.bumpversion.files]]
filename = ".cookiecutterrc"
search = "version: {current_version}"
replace = "version: {new_version}"
