image: python:3.9

default:
  tags:
    - small

before_script:
  # - python -V
  # - pip install tox

stages:
  - quality


coverage test:
  stage: quality
  script:
    - python -V
    - pip install tox
    - tox run -e clean,py39,report
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - htmlcov/
      - coverage.xml
    reports:
      junit: toxtests.xml


sonarqube-check:
  stage: quality
  needs: ["coverage test"]
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - tox run -e sonar
  allow_failure: true
  only:
    - merge_requests
    - main
    - develop
  artifacts:
    paths:
      - pylint-report.txt
      - coverage.xml

