image: python:3.9

default:
  tags:
    - small

before_script:
  - python -V
  - pip install tox

stages:
  - test

test:
  stage: test
  script:
    - tox -e clean,py39,report
  artifacts:
    paths:
      - htmlcov/
    reports:
      junit: toxtests.xml


