image: python:latest

default:
  tags:
    - small

before_script:
  - python -V
  - pip install tox

stages:
  - test
  - report

test:
  stage: test
  script:
    - tox -e py38-nocov,py311-nocov
  artifacts:
    reports:
      junit: toxtests.xml

coverage test:
  stage: report
  script:
    - tox -e py311-cover,report
  artifacts:
    paths:
      - htmlcov/
    reports:
      junit: toxtests.xml


