image: python:3.9

default:
  tags:
    - small

before_script:
  - python -V
  - pip install tox

stages:
  - test
  - report

test:
  stage: test
  script:
    - tox -e py12
  artifacts:
    reports:
      junit: toxtests.xml

coverage test:
  stage: report
  script:
    - tox -e report
  artifacts:
    paths:
      - htmlcov/
    reports:
      junit: toxcovtests.xml


