image: python:3.9

default:
  tags:
    - small

before_script:
  - python -V
  - pip install tox

stages:
  - test

test:
  stage: test
  script:
    - tox -e py39
  artifacts:
      paths:
      - $CI_PROJECT_DIR
      expire_in: 1 week 

